version: "3.9"

services:
  wotlk:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    container_name: wotlk
    environment:
      - WINEDEBUG=-all
      - DISPLAY=:99
      # Performance optimizations
      - LIBGL_ALWAYS_SOFTWARE=1
      - GALLIUM_DRIVER=llvmpipe
      - WINEDLLOVERRIDES=mscoree,mshtml=
      # Real FPS boost optimizations
      - __GL_SYNC_TO_VBLANK=0
      - MESA_NO_ERROR=1
      - MESA_GLTHREAD=true
      - __GL_THREADED_OPTIMIZATIONS=1
      - MESA_GL_VERSION_OVERRIDE=4.5
      - MESA_GLSL_VERSION_OVERRIDE=450
      - LP_NUM_THREADS=2
      - WINEESYNC=1
      - WINEFSYNC=1
    volumes:
      - /Users/dk/Documents/GitHub/open-ah-agent/data/CLIENT_WOTLK:/data:rw
      # Add shared memory for better performance
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"   # VNC
      - "6080:6080"   # noVNC (web)
    # Performance tuning (optimized for 4GB RAM, 2 CPU VPS)
    shm_size: "1gb"
    mem_limit: "4g"
    cpus: "2"
    restart: unless-stopped
    # Optimized startup sequence
    command: >
      bash -c "
        # Set performance governor
        echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 2>/dev/null || true
        
        # Start virtual display with maximum FPS settings
        Xvfb :99 -screen 0 1280x720x16 -ac +extension GLX +render -noreset -nolisten tcp -dpi 96 +extension DAMAGE -fbdir /dev/shm -maxclients 256 &
        sleep 1
        
        # Start optimized window manager
        fluxbox -rc /dev/null &
        sleep 1
        
        # Start VNC server with FPS-focused optimizations
        x11vnc -display :99 -forever -shared -nopw -rfbport 5900 -noxdamage -noxfixes -nowf -noscr -threads &
        sleep 1
        
        # Start noVNC web proxy
        websockify --web=/usr/share/novnc/ 6080 localhost:5900 &
        sleep 1
        
        # Start WoW with maximum performance settings
        cd /data
        WINEDEBUG=-all WINEPREFIX=/home/wineuser/.wine wine WoW.exe -opengl -gxapi opengl -gxwindow -gxresolution 1280x720 -nosound &
        
        # Keep container alive
        wait
      "

