server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
        filters:
          - name: network
            values: ["wowbox-network"]
          - name: label
            values: ["logging=promtail"]

    relabel_configs:
      - source_labels: [__meta_docker_container_label_logging]
        regex: promtail
        action: keep

      - target_label: job
        replacement: wowbox

      - source_labels: [__meta_docker_container_label_agent]
        target_label: agent

      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container

      - target_label: source
        replacement: docker

    pipeline_stages:
      - docker: {}

      # Parse Loguru-style prefix:
      # 2025-08-24 18:02:36.039 | INFO     | open_...:... - <message>
      - regex:
          expression: '^(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+)\s+\|\s+(?P<level>[A-Z]+)\s+\|\s+(?P<logger>[^|]+?)\s*-\s*(?P<message>.*)$'

      - labels:
          level:
          logger:

      # Keep only the message text as the log line content
      - output:
          source: message
